services: 
    mysql:
        image: mysql:8.0
        volumes:
          - kanban-mysql-data:/var/lib/mysql
        ports:
          - 127.0.0.1:3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: 12345678
          MYSQL_DATABASE: kanban

    back_net:
        image: frcol/kanban_net
        ports:
          - 127.0.0.1:5000:80
        environment:
          MYSQL_HOST: mysql
          MYSQL_USER: root
          MYSQL_PASSWORD: 12345678
          MYSQL_DB: kanban
          TOKEN_KEY: 0nwau0rmiUjdskjd9jdIOjdlNLKD7D*&Daewur293749283sdhf

    app:
        image: frcol/kanban_react
        ports: 
        - 127.0.0.1:3000:80

volumes:
    kanban-mysql-data: